// app/layout.tsx
import "./globals.css";
import Script from "next/script";
import type { Metadata } from "next";
import localFont from 'next/font/local';
import { Toaster } from "@/components/ui/sonner"
import { AuthProvider } from "@/contexts/AuthContext";
import { CartProvider } from "@/contexts/CartContext";
import { FavoritesProvider } from "@/contexts/FavoritesContext";

const elemental = localFont({
  src: '../public/fonts/elemental-end.ttf',
  display: 'swap',
  variable: '--font-elemental',
  weight: '400', 
  style: 'normal',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${elemental.variable} antialiased`}>
        {/* Meta Pixel */}
        <Script
          id="meta-pixel"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              <!-- Meta Pixel Code -->
              <script>
              !function(f,b,e,v,n,t,s)
              {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
              n.callMethod.apply(n,arguments):n.queue.push(arguments)};
              if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
              n.queue=[];t=b.createElement(e);t.async=!0;
              t.src=v;s=b.getElementsByTagName(e)[0];
              s.parentNode.insertBefore(t,s)}(window, document,'script',
              'https://connect.facebook.net/en_US/fbevents.js');
              fbq('init', '1739059187053230');
              fbq('track', 'PageView');
              </script>
              <noscript><img height="1" width="1" style="display:none"
              src="https://www.facebook.com/tr?id=1739059187053230&ev=PageView&noscript=1"
              /></noscript>
              <!-- End Meta Pixel Code -->
            `,
          }}
        />

        <AuthProvider>
          <CartProvider>
            <FavoritesProvider>
              {children}
              <Toaster position="top-right" />
            </FavoritesProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}