export {default as OtpForm} from "./OtpForm";
export {default as LoginForm} from "./LoginForm";
export {default as ProfileForm} from "./ProfileForm";
export {default as ContactUsForm} from "./ContactUsForm";
export {default as PreferenceForm} from "./PreferenceForm";
export {default as MeasurementForm} from "./MeasurementForm";
export {default as ResetPasswordForm} from "./ResetPasswordForm";
export {default as PartnerSignUpForm} from "./PartnerSignUpForm";
export {default as ForgotPasswordForm} from "./ForgotPasswordForm";