import { MigrationInterface, QueryRunner, TableColumn } from "typeorm"; // Import TableColumn if not already there

export class UpdateCreditCardsTable1752663930362 implements MigrationInterface {
    name = 'UpdateCreditCardsTable1752663930362'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Drop existing foreign key (as generated by TypeORM)
        await queryRunner.query(`ALTER TABLE \`credit_cards\` DROP FOREIGN KEY \`FK_316ec479135fbc369ccf229dd0f\``);

        // Add the missing cardBrand column
        // Ensure the type and length match your CreditCard entity's @Column definition
        await queryRunner.addColumn('credit_cards', new TableColumn({
            name: 'cardBrand',
            type: 'varchar',
            length: '50', // Match the length from your entity
            isNullable: false, // Or true, depending on your entity's @Column config
            // If you have existing rows, you might need a default value here:
            // default: "'unknown'",
        }));

        // Existing generated queries
        await queryRunner.query(`ALTER TABLE \`credit_cards\` CHANGE \`expiryMonth\` \`expiryMonth\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`credit_cards\` CHANGE \`expiryYear\` \`expiryYear\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`credit_cards\` ADD UNIQUE INDEX \`IDX_a358a26def849b562cd49465fd\` (\`paymentGatewayToken\`)`);
        await queryRunner.query(`ALTER TABLE \`credit_cards\` CHANGE \`userId\` \`userId\` varchar(36) NOT NULL`);
        await queryRunner.query(`CREATE INDEX \`IDX_8c08402a67a5099917aa3e3fbf\` ON \`credit_cards\` (\`last4\`)`);
        
        // Re-add the foreign key with ON DELETE CASCADE
        await queryRunner.query(`ALTER TABLE \`credit_cards\` ADD CONSTRAINT \`FK_316ec479135fbc369ccf229dd0f\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Drop the foreign key (if it was added in up)
        await queryRunner.query(`ALTER TABLE \`credit_cards\` DROP FOREIGN KEY \`FK_316ec479135fbc369ccf229dd0f\``);
        
        // Drop the cardBrand column (to revert the up change)
        await queryRunner.dropColumn('credit_cards', 'cardBrand');

        // Existing generated queries (in reverse order of up)
        await queryRunner.query(`DROP INDEX \`IDX_8c08402a67a5099917aa3e3fbf\` ON \`credit_cards\``);
        await queryRunner.query(`ALTER TABLE \`credit_cards\` CHANGE \`userId\` \`userId\` varchar(36) NULL`); // Assuming it was nullable before
        await queryRunner.query(`ALTER TABLE \`credit_cards\` DROP INDEX \`IDX_a358a26def849b562cd49465fd\``);
        await queryRunner.query(`ALTER TABLE \`credit_cards\` CHANGE \`expiryYear\` \`expiryYear\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`credit_cards\` CHANGE \`expiryMonth\` \`expiryMonth\` int NULL`);
        
        // Re-add the foreign key as it was before (if needed, or simply omit if dropping table)
        // Note: The original down method re-added the FK without ON DELETE CASCADE, which might be incorrect for a full revert.
        // If your original schema didn't have ON DELETE CASCADE, this line is fine.
        await queryRunner.query(`ALTER TABLE \`credit_cards\` ADD CONSTRAINT \`FK_316ec479135fbc369ccf229dd0f\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
