import { MigrationInterface, QueryRunner, TableColumn } from 'typeorm';

// NOTE: Replace the class name with the one generated by your TypeORM CLI (e.g., with a timestamp)
export class AddTagColumnsToSubcategoryTables1759808171389 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        // --- Add columns to subcategory_item table ---
        await queryRunner.addColumns('subcategory_item', [
            new TableColumn({
                name: 'tags_required',
                type: 'text', // TypeORM uses 'text' or 'simple-array' maps to TEXT/VARCHAR in MySQL for simple-array
                isNullable: true,
            }),
            new TableColumn({
                name: 'optional_tags',
                type: 'text',
                isNullable: true,
            }),
            new TableColumn({
                name: 'tag_defaults',
                type: 'json', // ✅ CORRECTED: Use 'json' type for MySQL
                isNullable: true,
            }),
        ]);

        // --- Add columns to subcategory_item_child table ---
        await queryRunner.addColumns('subcategory_item_child', [
            new TableColumn({
                name: 'tags_required',
                type: 'text',
                isNullable: true,
            }),
            new TableColumn({
                name: 'optional_tags',
                type: 'text',
                isNullable: true,
            }),
            new TableColumn({
                name: 'tag_defaults',
                type: 'json', // ✅ CORRECTED: Use 'json' type for MySQL
                isNullable: true,
            }),
        ]);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // --- Remove columns from subcategory_item_child table ---
        await queryRunner.dropColumns('subcategory_item_child', ['tags_required', 'optional_tags', 'tag_defaults']);

        // --- Remove columns from subcategory_item table ---
        await queryRunner.dropColumns('subcategory_item', ['tags_required', 'optional_tags', 'tag_defaults']);
    }
}