import { MigrationInterface, QueryRunner, TableColumn } from 'typeorm';

export class AddMobileLevel1ToSubcategory1760599896383 implements MigrationInterface {
    // You should replace '1678886400000' with the actual timestamp generated by the TypeORM CLI.

    public async up(queryRunner: QueryRunner): Promise<void> {
        // SQL to add the new column 'mobileLevel1' to the 'subcategory' table.
        // It's defined as a non-nullable string (@Column() mobileLevel1: string;)
        await queryRunner.addColumn(
            'subcategory',
            new TableColumn({
                name: 'mobileLevel1',
                type: 'varchar', // Use 'varchar' for string columns in most SQL dialects
                isNullable: true, // Matches the non-nullable @Column() decorator
            }),
        );
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // SQL to remove the column, used for rolling back the migration.
        await queryRunner.dropColumn('subcategory', 'mobileLevel1');
    }
}