import { MigrationInterface, QueryRunner, TableColumn } from 'typeorm';

export class AddMobileLevel3ToSubcategoryItemChild1760630894541 implements MigrationInterface {
    // ⚠️ IMPORTANT: Replace '1678886400000' with the actual timestamp generated by the TypeORM CLI.

    public async up(queryRunner: QueryRunner): Promise<void> {
        // SQL to add the new column 'mobileLevel3' to the 'subcategory_item_child' table.
        // Assuming your table name is 'subcategory_item_child' (TypeORM default).
        await queryRunner.addColumn(
            'subcategory_item_child', // Table name
            new TableColumn({
                name: 'mobileLevel3',
                type: 'varchar', // Appropriate type for a string in MySQL
                isNullable: true, // Set to true as defined in the entity
            }),
        );
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // SQL to remove the column for rolling back the migration.
        await queryRunner.dropColumn('subcategory_item_child', 'mobileLevel3');
    }
}