import { MigrationInterface, QueryRunner, TableColumn } from 'typeorm';

export class AddMobileLevel2ToSubcategoryItem1760623855397 implements MigrationInterface {
    // IMPORTANT: Replace '1678886400000' with the actual timestamp generated by the TypeORM CLI.

    public async up(queryRunner: QueryRunner): Promise<void> {
        // SQL to add the new column 'mobileLevel2' to the 'subcategory_item' table.
        // Assuming your table name is 'subcategory_item' (TypeORM default for SubcategoryItem).
        // If your table name is different, adjust the first parameter of addColumn.
        await queryRunner.addColumn(
            'subcategory_item',
            new TableColumn({
                name: 'mobileLevel2',
                type: 'varchar', // Appropriate type for a string in MySQL
                isNullable: true, // IMPORTANT: Set to true as defined in the entity
            }),
        );
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // SQL to remove the column for rolling back the migration.
        await queryRunner.dropColumn('subcategory_item', 'mobileLevel2');
    }
}